import React,{useEffect,useState} from 'react';
import Icon from './Icon';
import {api} from '../lib/api';
import {normalizeLiveMatches} from '../lib/liveScores.js';
export default function LiveScores(){
const[matches,setMatches]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
const load=async()=>{setLoading(true);setError('');try{setMatches(normalizeLiveMatches(await api.live()));}catch(err){setError(err.message||'Unable to load live scores');}finally{setLoading(false);}};
useEffect(()=>{load();},[]);
return <section className="card"><div className="card-header"><div><h2 className="card-title">Live match center</h2><p className="card-subtitle">Live feed from the configured cricket score service</p></div><button className="btn btn-soft" onClick={load}><Icon name="refresh" size={14}/> Refresh</button></div>{error&&<div style={{padding:'0 20px'}}><div className="alert alert-error">{error}</div></div>}{loading?<div className="empty"><div className="empty-copy">Loading live matches…</div></div>:matches.length===0?<div className="empty"><div className="empty-icon"><Icon name="activity"/></div><div className="empty-title">No live matches right now</div><div className="empty-copy">The live feed is empty. Check again when matches are in progress.</div></div>:<div className="live-grid">{matches.map((match,index)=><article className="live-card" key={(match.id||'live')+'-'+index}><div className="live-top"><span className="badge badge-live">{match.status||'Live'}</span><span className="card-subtitle">{match.series||'Tournament feed'}</span></div><div className="team-name" style={{marginTop:14}}>{match.name}</div><div className="live-score"><div className="live-team"><span>{match.homeTeam}</span><strong>{match.homeScore||'—'}</strong></div><div className="live-team"><span>{match.awayTeam}</span><strong>{match.awayScore||'—'}</strong></div></div>{match.venue&&<div className="result-note">{match.venue}</div>}</article>)}</div>}</section>;
}