import React,{useEffect,useMemo,useState} from 'react';
import Icon from './Icon';
import {api} from '../lib/api';

export default function PointsTable(){
 const[standings,setStandings]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const data=await api.standings();setStandings((Array.isArray(data)?data:[]).map((team)=>({...team,teamName:team.teamName||team.name||'Unknown Team',captain:team.captain||'TBD',matchesPlayed:team.matchesPlayed??team.matches_played??0,wins:team.wins??0,losses:team.losses??0,points:team.points??0})));}catch(err){setError(err.message||'Unable to load standings');}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const leader=standings[0];const totalPoints=useMemo(()=>standings.reduce((sum,t)=>sum+t.points,0),[standings]);
 return <section className="section-grid"><div className="standings-hero"><div><span className="hero-kicker">Competition rankings</span><h2>Points table</h2><p>Every completed result feeds the live tournament ranking.</p></div><div className="standings-total"><small>Total points</small><strong>{loading?'—':totalPoints}</strong></div></div>
 <section className="card"><div className="card-header"><div><h2 className="card-title">Tournament standings</h2><p className="card-subtitle">Rankings update as match results are recorded</p></div><div className="filter-tabs"><span className="badge badge-neutral">{standings.length} teams</span><button className="refresh-btn" onClick={load} aria-label="Refresh standings"><Icon name="refresh" size={13}/></button></div></div>
 {error&&<div style={{padding:'0 20px'}}><div className="alert alert-error">{error}</div></div>}{loading?<div className="empty"><div className="empty-copy">Loading standings…</div></div>:standings.length===0?<div className="empty"><div className="empty-icon"><Icon name="trophy"/></div><div className="empty-title">No standings yet</div><div className="empty-copy">Register teams and complete matches to build the leaderboard.</div></div>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Rank</th><th>Team</th><th>Captain</th><th>Played</th><th>Won</th><th>Lost</th><th>Points</th></tr></thead><tbody>{standings.map((team,index)=><tr key={team.id||team.teamName}><td><span className={'rank '+(index===0?'first':'')}>{index+1}</span></td><td><strong>{team.teamName}</strong></td><td>{team.captain}</td><td>{team.matchesPlayed}</td><td>{team.wins}</td><td>{team.losses}</td><td><strong>{team.points}</strong></td></tr>)}</tbody></table></div>}</section>
 {leader&&<div className="leader-note"><span className="stat-icon"><Icon name="trophy" size={15}/></span><div><strong>{leader.teamName}</strong> currently leads the table</div><span>{leader.points} pts</span></div>}
 </section>;
}