import React,{useEffect,useState} from 'react';
import Icon from './Icon';
import {api} from '../lib/api';

export default function TeamManagement(){
 const[teams,setTeams]=useState([]);const[teamName,setTeamName]=useState('');const[captain,setCaptain]=useState('');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState({type:'',text:''});
 const load=async()=>{setLoading(true);try{const data=await api.teams();setTeams((Array.isArray(data)?data:[]).map((team)=>({...team,teamName:team.teamName||team.name||'Unknown Team',captain:team.captain||'TBD'})));}catch(err){setMessage({type:'error',text:err.message||'Unable to load teams'});}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const submit=async(event)=>{event.preventDefault();if(!teamName.trim()||!captain.trim())return setMessage({type:'error',text:'Team name and captain are required.'});setSaving(true);setMessage({type:'',text:''});try{const team=await api.createTeam({name:teamName.trim(),teamName:teamName.trim(),captain:captain.trim()});setTeams((current)=>[...current,{...team,teamName:team?.teamName||teamName.trim(),captain:team?.captain||captain.trim()}]);setTeamName('');setCaptain('');setMessage({type:'success',text:'Team registered successfully.'});}catch(err){setMessage({type:'error',text:err.message||'Unable to register team'});}finally{setSaving(false);}};
 return <div className="form-layout">
  <section className="card form-card"><div className="form-kicker"><span className="stat-icon"><Icon name="users" size={16}/></span><span>Roster setup</span></div><h2 className="form-title" style={{marginTop:14}}>Register a team</h2><p className="form-copy">Add a participating team and captain. The roster becomes available for fixture scheduling immediately.</p>
   <form onSubmit={submit}><div className="field"><label htmlFor="team-name">Team name</label><input className="input" id="team-name" value={teamName} onChange={(e)=>setTeamName(e.target.value)} placeholder="e.g. Coastal Strikers"/></div><div className="field"><label htmlFor="captain-name">Captain</label><input className="input" id="captain-name" value={captain} onChange={(e)=>setCaptain(e.target.value)} placeholder="e.g. Arjun Reddy"/></div>{message.text&&<div className={'alert '+(message.type==='error'?'alert-error':'alert-success')}>{message.text}</div>}<button className="btn btn-dark btn-full" style={{marginTop:14}} disabled={saving}>{saving?'Registering…':'Register team'}<Icon name="arrow" size={13}/></button></form>
  </section>
  <section className="card"><div className="card-header"><div><h2 className="card-title">Tournament roster</h2><p className="card-subtitle">Teams currently eligible for fixtures</p></div><span className="badge badge-neutral">{teams.length} teams</span></div>
   {loading?<div className="empty"><div className="empty-copy">Loading roster…</div></div>:teams.length===0?<div className="empty"><div className="empty-icon"><Icon name="users"/></div><div className="empty-title">No teams registered</div><div className="empty-copy">Use the form to create your first tournament team.</div></div>:<div className="team-grid">{teams.map((team,index)=><article className="team-card" key={team.id||team.teamName}><div className="team-card-top"><div className="team-avatar">{String(index+1).padStart(2,'0')}</div><span className="badge badge-success">Active</span></div><div className="team-card-name">{team.teamName}</div><div className="team-card-meta">Captain · {team.captain}</div><div className="team-card-footer"><span>Roster position {index+1}</span><Icon name="arrow" size={12}/></div></article>)}</div>}
  </section>
 </div>;
}